name: Solar System Workflow

on:
    workflow_dispatch:
    push:
        branches:
            - main
            - 'feature/*'
env:
    MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
    MONGO_USERNAME: ${{vars.MONGO_USERNAME}}
    MONGO_PASSWORD: ${{secrets.MONGO_PASSWORD}}
jobs:
    unit-testing:
        name: Unit-Testing
        strategy:
          matrix:
            nodejs_version: [18, 19, 24]
            operating_system: [ubuntu-latest, macos-latest]
            exclude:
              - nodejs_version: 18
                operating_system: macos-latet

        runs-on: ${{matrix.operating_system}}
        steps:
            - name: Checkout Repo
              uses: actions/Checkout@v6
              
            - name: Setup NodeJS Version - ${{matrix.nodejs_version}}
              uses: actions/setup-node@v3
              with:
                node-version: ${{matrix.nodejs_version}}
            - name: Install Depencies
              run: npm install

            - name: Run Unit Testing
              run : npm test
            
            - name: Archive Test Result
              uses: actions/upload-artifact@v4
              with:
                name: Mocha-Test-Result- ${{matrix.nodejs_version}}
                path: test-results-${{matrix.nodejs_version}}.xml

    code-coverage:
        name: Code Coverage
        runs-on: ubuntu-latest
        steps:
          - name: Checkout Repository
            uses: actions/checkout@v6

          - name: Setup NodeJs Version - 24
            uses: actions/setup-node@v3
            with:
              node-version: 24

          - name: Install dependencies
            run: npm install

          - name: Check Code Coverage
            continue-on-error: true
            run: npm run coverage
          
          - name: Archive Test Result
            uses: actions/upload-artifact@v4
            with:
              name: Code-Coverage Result
              path: covergae
              retention-days: 5
        